on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  continuous_deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 15
      - run: yarn
      - run: yarn generate
      - run: touch ./dist/.nojekyll
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
